### ISSUE TITLE
Upgrade gcloud dependency to latest version of google-cloud

### ISSUE THREAD

**Issue by bjwatson** [googleapis/artman#103]
### What

Upgrade `gcloud` dependency to latest version of `google-cloud` (currently `0.20.x`).
### Why
1. Dependency issues: See https://github.com/googleapis/artman/issues/102 for context.
2. Stop using Logging v1, which is deprecated.

**Comment by ethanbao** [comment]
Should have been upgraded. Please reopen if still seeing this problem.
