### ISSUE TITLE
Remove default --jobboard_name from start_conductor.py

### ISSUE THREAD

**Issue by bjwatson** [googleapis/artman#104]
### What:

Remove default `--jobboard_name` from `start_conductor.py`.
### Why:

The default is `remote`, which should be exclusively used by our remote build server. I just ran `start_conductor.py` on my workstation, and it ate a bunch of messages from Zookeeper server.

**Comment by ethanbao** [comment]
Became obsolete as we no longer use the zookeeper based remote execution.
