### ISSUE TITLE
Tests fail if TOOLKIT_HOME is set

### ISSUE THREAD

**Issue by geigerj** [googleapis/artman#106]
### What

If the environment variable `TOOLKIT_HOME` is set, the tests fail because they expect toolkit to be located in the fake test directory, but the environment variable overrides this location. The tests should ignore the environment so that they are deterministic.
### Why

Tests should be deterministic independent of environment.

/cc @swcloud

**Comment by lukesneeringer** [comment]
`TOOLKIT_HOME` is gone. Closing.
