### ISSUE TITLE
Baseline tests don't capture gRPC plugin

### ISSUE THREAD

**Issue by geigerj** [googleapis/artman#119]
#118 fixes a breakage in the Ruby gRPC pipeline, but the baseline tests don't reflect that; the actual pipeline passes the gRPC plugin parameter value, but the test pipeline doesn't. Investigate why not.

Original report from @swcloud:

> Hey Jacob, I just updated artman to be the latest and when I run pipeline with task 'GrpcClientPipeline' for ruby and 'logging' API. I got the following error:
Final args:
  package_defaults_yaml : ../googleapis/gapic/packaging/api_defaults.yaml
  repo_root : ..
  package_dependencies_yaml : ../googleapis/gapic/packaging/dependencies.yaml
  language : ruby
  stage_output : False
  import_proto_path : ['../googleapis']
  enable_batch_generation : True
  gapic_api_yaml : ['../googleapis/google/logging/v2/logging_gapic.yaml']
  common_protos_yaml : ../googleapis/gapic/packaging/common_protos.yaml
  toolkit_path : ../toolkit
  skip_packman : True
  api_name : google-cloud-logging-v2
  output_dir : ../artman/output
  final_repo_dir : ../google-cloud-ruby/google-cloud-logging
  staging_repo_dir : ../api-client-staging/generated
  src_proto_path : ['../googleapis/google/logging/v2']
  service_yaml : ['../googleapis/google/logging/logging.yaml']
  gapic_language_yaml : ['../googleapis/gapic/lang/ruby_gapic.yaml']
  proto_gen_pkg_deps : ['google-common-protos']
Create GrpcClientPipeline instance.
Searching for latest protobuf source
/Users/songwang/homebrew/bin/grpc_ruby_plugin: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).

> Traceback (most recent call last):
  File "execute_pipeline.py", line 239, in <module>
    main(sys.argv[1:])
  File "execute_pipeline.py", line 87, in main
    engine.run()
  File "/Users/songwang/IdeaProjects/vtk/artman/.tox/py27/lib/python2.7/site-packages/taskflow/engines/action_engine/engine.py", line 159, in run
    for _state in self.run_iter():
  File "/Users/songwang/IdeaProjects/vtk/artman/.tox/py27/lib/python2.7/site-packages/taskflow/engines/action_engine/engine.py", line 223, in run_iter
    failure.Failure.reraise_if_any(it)
  File "/Users/songwang/IdeaProjects/vtk/artman/.tox/py27/lib/python2.7/site-packages/taskflow/types/failure.py", line 292, in reraise_if_any
    failures[0].reraise()

**Comment by geigerj** [comment]
@swcloud Why is this closed? Was there a PR that fixed it?

**Comment by swcloud** [comment]
Didn't you fix it here: https://github.com/googleapis/artman/pull/120?

**Comment by geigerj** [comment]
@swcloud yup, for an unknown reason the existing tests did not catch the issue that required #120 -- it might still be worth investigating why.

**Comment by ethanbao** [comment]
We now have smoketest to capture this.
