### ISSUE TITLE
PythonChangePackageTask temporary files referenced in gRPC generated code

### ISSUE THREAD

**Issue by geigerj** [googleapis/artman#121]
### What

`PythonChangePackageTask` creates temporary proto files; these temporary files are referenced in the `source` comment of the generated gRPC Python code rather than the true source proto ([example](https://github.com/googleapis/api-client-staging/pull/118/files/2bcd2875a578ae525d2aabb862cf9c131b4665f5#diff-d7392ffc12163055451f586579c0cd5dL2)).

### Why

It's confusing to have final, end-user-visible code reference an intermediate, temporary file. Note that this affects comments in the generated code only; there is no behavior caused by this issue.

**Comment by ethanbao** [comment]
@landrito, is this still a problem? If not, please close this issue.

**Comment by landrito** [comment]
@geigerj I don't remember what this issue was about maybe you do?

**Comment by geigerj** [comment]
It was a super minor issue where a comment at the top of the `_pb2` files referenced a path to the source proto they were generated from, but because artman manipulates the proto files for Python, that path didn't actually exist. My guess, unless `PythonChangePackageTask` has changed, is that this is still happens but we probably don't actually care because I'd be surprised if anyone is reading the source comments for the `_pb2`. I'd leave this open and at P3 priority.

**Comment by geigerj** [comment]
Unassigning -- this sort of low-priority but is more appropriate for a fixit.

**Comment by vchudnov-g** [comment]
Closing given the low priority and the upcoming move away from artman
