### ISSUE TITLE
Clear api-client-staging with stage_output flag

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/artman#141]
The --stage_output flag should clear the api-client-staging repo before copying files. Otherwise in cases such as a file rename we will end up with stale files.

**Comment by shinfan** [comment]
I will send PR to fix this.

**Comment by lukesneeringer** [comment]
@michaelbausor @shinfan I believe my new `--publish local` and `--publish github` both handle this case correctly. Can I close this?

**Comment by shinfan** [comment]
Feel free to close this issue if your new publish task clear the repo before copying files.

**Comment by lukesneeringer** [comment]
It does ([local][], [github][]).

  [local]: https://github.com/googleapis/artman/blob/master/artman/tasks/publish/local.py#L59
  [github]: https://github.com/googleapis/artman/blob/master/artman/tasks/publish/github.py#L84-L85
