### ISSUE TITLE
Integration test failure

### ISSUE THREAD

**Issue by swcloud** [googleapis/artman#155]
When doing 'tox -e py27', there are errors showing as below

$ tox -e py27
py27 installed: appdirs==1.4.3,automaton==1.8.0,Babel==2.4.0,cachetools==2.0.0,colorlog==2.10.0,configparser==3.5.0,contextlib2==0.5.4,coverage==4.3.4,debtcollector==1.13.0,decorator==4.0.11,enum34==1.1.6,extras==1.0.0,fasteners==0.14.1,fixtures==3.0.0,flake8==3.2.1,funcsigs==1.0.2,functools32==3.2.3.post2,futures==3.0.5,futurist==1.0.0,gcloud==0.15.0,google-apitools==0.5.8,googleapis-common-protos==1.5.2,grpcio==1.2.1,grpcio-tools==1.2.1,httplib2==0.10.3,iso8601==0.1.11,jsonschema==2.6.0,kazoo==2.2.1,linecache2==1.0.0,mccabe==0.5.3,mock==2.0.0,monotonic==1.3,mox3==0.21.0,msgpack-python==0.4.8,netaddr==0.7.19,netifaces==0.10.5,networkx==1.11,oauth2client==3.0.0,oslo.i18n==3.15.0,oslo.serialization==2.18.0,oslo.utils==3.25.0,packaging==16.8,pbr==2.0.0,prettytable==0.7.2,protobuf==3.2.0,py==1.4.33,pyasn1==0.2.3,pyasn1-modules==0.0.8,pycodestyle==2.2.0,pyfakefs==2.9,pyflakes==1.3.0,pyparsing==2.2.0,pytest==3.0.7,pytest-cov==2.4.0,pytest-timeout==1.2.0,python-mimeparse==1.6.0,pytz==2017.2,PyYAML==3.12,requests==2.13.0,rsa==3.4.2,six==1.10.0,stevedore==1.21.0,taskflow==1.25.0,testtools==2.2.0,traceback2==1.4.0,unittest2==1.1.0,wrapt==1.10.10,yapf==0.16.1
py27 runtests: PYTHONHASHSEED='3329163374'
py27 runtests: commands[0] | py.test -rxs --timeout=30 --cov --cov-report= --cov-append /Users/songwang/IdeaProjects/vtk/artman/
========================================================= test session starts ==========================================================
platform darwin -- Python 2.7.10, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /Users/songwang/IdeaProjects/vtk/artman, inifile:
plugins: timeout-1.2.0, cov-2.4.0
timeout: 30.0s method: signal
collected 33 items 
test/test_gapic_conductor.py F
test/test_goimport_task.py .
test/test_io_tasks.py ..
test/test_package_metadata_task.py .
test/test_pipeline_baseline.py ........................
test/test_python_package_change_task.py ...
test/utils/test_github_utils.py .
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/songwang/IdeaProjects/vtk/artman/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 98, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/songwang/IdeaProjects/vtk/artman/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 133, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/songwang/IdeaProjects/vtk/artman/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/songwang/IdeaProjects/vtk/artman/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/songwang/IdeaProjects/vtk/artman/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/Users/songwang/IdeaProjects/vtk/artman/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "/Users/songwang/IdeaProjects/vtk/artman/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
INTERNALERROR>     wrap_controller.send(call_outcome)
INTERNALERROR>   File "/Users/songwang/IdeaProjects/vtk/artman/.tox/py27/lib/python2.7/site-packages/pytest_cov/plugin.py", line 232, in pytest_runtestloop
INTERNALERROR>     self.cov_controller.finish()
INTERNALERROR>   File "/Users/songwang/IdeaProjects/vtk/artman/.tox/py27/lib/python2.7/site-packages/pytest_cov/engine.py", line 150, in finish
INTERNALERROR>     self.cov.combine()
INTERNALERROR>   File "/Users/songwang/IdeaProjects/vtk/artman/.tox/py27/lib/python2.7/site-packages/coverage/control.py", line 767, in combine
INTERNALERROR>     self.get_data()
INTERNALERROR>   File "/Users/songwang/IdeaProjects/vtk/artman/.tox/py27/lib/python2.7/site-packages/coverage/control.py", line 795, in get_data
INTERNALERROR>     self.collector.save_data(self.data)
INTERNALERROR>   File "/Users/songwang/IdeaProjects/vtk/artman/.tox/py27/lib/python2.7/site-packages/coverage/collector.py", line 360, in save_data
INTERNALERROR>     covdata.add_arcs(abs_file_dict(self.data))
INTERNALERROR>   File "/Users/songwang/IdeaProjects/vtk/artman/.tox/py27/lib/python2.7/site-packages/coverage/data.py", line 365, in add_arcs
INTERNALERROR>     raise CoverageException("Can't add arcs to existing line data")
INTERNALERROR> CoverageException: Can't add arcs to existing line data
================================================= 1 failed, 32 passed in 25.12 seconds =================================================
ERROR: InvocationError: '/Users/songwang/IdeaProjects/vtk/artman/.tox/py27/bin/py.test -rxs --timeout=30 --cov --cov-report= --cov-append /Users/songwang/IdeaProjects/vtk/artman/'
_______________________________________________________________ summary ________________________________________________________________
ERROR:   py27: commands failed

**Comment by lukesneeringer** [comment]
I completely redid the unit test running in artman in #159. I am going to close this for now since I expect the toolchain changes likely fixed it, but if you are still getting this, please feel free to re-open.
