### ISSUE TITLE
"/" root is now allowed as "Local code path" during configure-artman step

### ISSUE THREAD

**Issue by ethanbao** [googleapis/artman#163]
"/" is the root when artman is running in docker/remote mode.

I can manually update the value in ~/.artman/config.yaml to "/" after initialization though.

**Comment by lukesneeringer** [comment]
Just pass `--reporoot=/`.
I can set that to happen automatically if `--remote` is issued.

**Comment by ethanbao** [comment]
We no longer support such remote execution mode. Mark it as obsolete.
