### ISSUE TITLE
Configuration merge semantics

### ISSUE THREAD

**Issue by geigerj** [googleapis/artman#175]
From @lukesneeringer's comment on #171:

> However, should we consider trying to have a standard format in our YAML for when we have common parameters with potential language overrides? This format seems to be distinct from the format used in `artman_{api}.yaml`.
> 
> I think, of the two, I prefer the other format, which comes down to:
> 
> ```yaml
> ---
> common:
>   foo: bar
>   baz:
>     spam: eggs
> python:
>   foo: bacon
>   baz:
>     hello: goodbye
> node:
>   baz:
>     spam: weeee!
> ```
> 
> Which Artman amalgamates together so that in Python, you get:
> 
> ```yaml
> ---
> foo: bacon
> baz:
>   spam: eggs
>   hello: goodbye
> ```
> 
> And in Node you get:
> 
> ```yaml
> ---
> foo: bar
> baz:
>   spam: weeeee!
> ```

**Comment by ethanbao** [comment]
I am not sure whether this issue has been addressed in the new artman config schema, in which one can define common config and artifact-specific (almost equivalent to language-specific) config. Can you confirm, Jacob?

**Comment by ethanbao** [comment]
@geigerj

**Comment by geigerj** [comment]
Agreed.
