### ISSUE TITLE
httplib2 dependency problem

### ISSUE THREAD

**Issue by garrettjonesgoogle** [googleapis/artman#188]
I just did `sudo pip install googleapis-artman`, and then when I try to run `artman --api logging --language java --publish local`, it says:

```
pkg_resources.DistributionNotFound: httplib2>=0.9.2,<1dev
```

And when I rerun the install, I see a line that says

```
Requirement already satisfied: httplib2>=0.8 in /usr/lib/python2.7/dist-packages (from google-apitools->googleapis-artman)
```

**Comment by ethanbao** [comment]
No longer seeing this issue, please reopen if you run into this again.
