### ISSUE TITLE
Consider encoding `paths` per-language

### ISSUE THREAD

**Issue by geigerj** [googleapis/artman#219]
### What

Currently the staging/publishing paths are configured in the artman config per-API x Lang. For most APIs, these are predictable, leading to some level of redundancy.

### How

Instead, we could considering configuring per-lang "path rules" that are automatically expanded per-API. We can allow per-API overrides for exceptional cases, e.g., LRO and non-primary API versions.

cc: @lukesneeringer

**Comment by ethanbao** [comment]
@geigerj, is this issue addressed by the new artman config schema?

**Comment by geigerj** [comment]
@ethanbao I don't think so, but I'm no longer sure this is a good idea. Closing as obsolete.
