### ISSUE TITLE
Consider raising exception on NodeJS gRPC pipeline

### ISSUE THREAD

**Issue by geigerj** [googleapis/artman#260]
### What

Consider raising an exception if GrpcClientPipeline is run for NodeJS. NodeJS doesn't generate a standalone gRPC client.

### Context

An Google-internal customer following attempted self-service generation gRPC clients for NodeJS and was confused when the pipeline resulted in no output.

**Comment by lukesneeringer** [comment]
Why does our self-service instruct the creation of a gRPC client in any language other than Java? It is a superfluous step in the other six languages now.

**Comment by lukesneeringer** [comment]
P. S. And even in Java, we should instruct the use of the flag that makes a single client, since most self-service use cases will be incompatible with pushing the gRPC packages to Maven.

**Comment by ethanbao** [comment]
Fix by https://github.com/googleapis/artman/pull/319
