### ISSUE TITLE
artman2 modifies your googleapis directory in-place

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/artman#275]
Running artman2 makes modifications to multiple YAML files in your googleapis directory and just leaves those modifications there.

Expected behavior: googleapis should be an input and should not be touched.

**Comment by ethanbao** [comment]
In theory, artman will only modify GAPIC yaml when someone run `artman ... generate gapic_config`. With GAPIC config advisor in-place, such overriding is not going to wipeout existing configs and their comments, but adding new ones (which are required in order for library to generate). With that, such in-place modification to gapic yaml is intended and desired. Thoughts, @lukesneeringer ?

**Comment by ethanbao** [comment]
I guess you were not running into this when generating gapic config. I tried to reproduce the issue by cloning googleapis repo and then running the following command under the googleapis directory:

    artman --config google/pubsub/artman_pubsub.yaml generate python_gapic

I don't see any file being modified. Could you provide a way to repro?

**Comment by lukesneeringer** [comment]
I do not remember what was going on here. Closing.
