### ISSUE TITLE
Investigate custom Ruby namespace for protoc output

### ISSUE THREAD

**Issue by geigerj** [googleapis/artman#288]
### What

Many GAPIC langauges have either a proto option (e.g., `java_package`) or an artman task (e.g., [`PythonChangePackageTask`](https://github.com/googleapis/artman/blob/cc5f1dc3a13b9b31aeb8d5adcd84cd9dab95aaeb/artman/tasks/python_grpc_tasks.py#L29)) to control the namespacing of the protoc output files. Investigate adding something similar for Ruby.

### Context

https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1750#issuecomment-332342221

**Comment by landrito** [comment]
Also note that this should affect the namespace that the grpc generated code is generated to.

**Comment by jbolinger** [comment]
The `ruby_package` was added in protoc. (https://github.com/google/protobuf/pull/4609 https://github.com/google/protobuf/pull/4627)

Closing since changes to artman are no longer required.
