### ISSUE TITLE
Running JavaGrpcClientPipeline doesn't work properly

### ISSUE THREAD

**Issue by omaray** [googleapis/artman#29]
When running the following command nothing happens:

python execute_pipeline.py --config '../googleapis/gapic/api/artman_yyyy.yaml:common|java,../googleapis/gapic/lang/common.yaml:default|java' JavaGrpcClientPipeline

Note: the string "yyyy" stands for a random api.

IMPACT
It seems like we are not able to generate the Java gRPC generated files at all.

EXPECTED RESULT
It should just work: we should get gRPC generated files in Java for a specific api.

ACTUAL RESULT
This is the output (notice that it stops when trying to locate the gRPC plugin for Java):

Final args:
  auto_resolve : True
  auto_merge : True
  import_proto_path : ['../googleapis/gapic/api/../..']
  gapic_api_yaml : ['../googleapis/gapic/api/../../google/yyyy/v1/yyyy_gapic.yaml']
  toolkit_path : ../toolkit
  final_repo_dir : ../gcloud-java/gcloud-java-yyyy
  api_name : yyyy-v1
  output_dir : ../artman/output
  gapic_language_yaml : ['../googleapis/gapic/lang/java_gapic.yaml']
  src_proto_path : ['../googleapis/gapic/api/../../google/yyyy/v1']
  service_yaml : ['../googleapis/gapic/api/../../google/yyyy/v1/yyyy.yaml']
  ignore_base : False
Create JavaGrpcClientPipeline instance.
Generating protos ../googleapis/gapic/api/../../google/yyy/v1
Searching for latest protobuf source
Running protoc with grpc plugin on ../googleapis/gapic/api/../../google/yyy/v1
Searching for latest protobuf source
start gradle process to locate GRPC Java plugin

**Comment by garrettjonesgoogle** [comment]
Actually I think this was never broken, the command just wasn't informative enough to say that it succeeded.
