### ISSUE TITLE
artman2 0.4.18 does not work without --local right now.

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/artman#290]
It needs to set the working directory within Docker to googleapis.

**Comment by ethanbao** [comment]
It would be helpful to give me an example command that used to work prior to this 0.4.18 release.

**Comment by ethanbao** [comment]
The following command worked for me. Can you help double confirm?

artman2 --image googleapis/artman:0.4.18 --config google/pubsub/artman_pubsub.yaml generate java_gapic

**Comment by ethanbao** [comment]
@lukesneeringer Luke, do you recall how to reproduce this issue?

**Comment by ethanbao** [comment]
I cloned the latest googleapis/googleapis repo and run the following command with latest artman version (0.5.1) in the local directory:

    artman --config google/pubsub/artman_pubsub.yaml generate python_gapic

I didn't run into any issue with library generation. Note: without --local, the real execution happens in docker.

**Comment by ethanbao** [comment]
Downgrade to P2 as it is not reproducible.

**Comment by lukesneeringer** [comment]
I am pretty sure (confidence: 95%) this is the issue Alex Fenster ran into last week. If you fixed it for him, then you can close this.

**Comment by ethanbao** [comment]
Thanks for confirming. Close this bug for now. Feel free to reopen if this problem comes up again.
