### ISSUE TITLE
Improve user config usability

### ISSUE THREAD

**Issue by geigerj** [googleapis/artman#305]
### What

`arman` is looking for `googleapis/gapic/lang/doc.yaml` relative to my working directory instead of relative to the `root-dir`. This effectively makes the root-dir useless.

### Repro

I ran `artman` from two levels above my `googleapis` dir:

```
~/repos$ artman --config gapi-dev/googleapis/google/bigtable/artman_bigtable.yaml --verbose generate ruby_gapic
```

My root-dir is specified in `~/.artman/config.yaml`:

```
...
root-dir: ~/repos/gapi-dev/googleapis
```

This fails with:

```
FileNotFoundError: [Errno 2] No such file or directory: '.../repos/googleapis/gapic/lang/doc.yaml'
```

**Comment by ethanbao** [comment]
Due to legacy reason, the field name in artman user config is not `root-dir` but `googleapis`. Could you please confirm whether it will work after you change your local user config?

Once you confirm that I will add changes to support `root-dir` in artman user config which will override `goolgeapis` if the former is specified.

**Comment by geigerj** [comment]
Still doesn't work.

.artman/config.yaml:
```
---                                                                                                                                                                                                       
publish: local
github:
  username: geigerj
  token: [redacted]
googleapis: ~/repos/gapi-dev/googleapis
```

I ran:
```
~$ pwd
/usr/local/google/home/jgeiger

~$ artman --config repos/gapi-dev/googleapis/google/logging/artman_logging.yaml --local generate ruby_gapic
Traceback (most recent call last):
  ...
  File "/usr/local/google/home/jgeiger/repos/gapi-dev/artman/artman/cli/main.py", line 58, in main
    pipeline_name, pipeline_kwargs = normalize_flags(flags, user_config)
  File "/usr/local/google/home/jgeiger/repos/gapi-dev/artman/artman/cli/main.py", line 365, in normalize_flags
    language=language, )
  File "/usr/local/google/home/jgeiger/repos/gapi-dev/artman/artman/utils/config_util.py", line 30, in load_config_spec
    with open(config_path) as config_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/google/home/googleapis/gapic/lang/doc.yaml'
```

**Comment by ethanbao** [comment]
Another refactoring to user-config would be needed. Under current implementation (https://github.com/googleapis/artman/blob/master/artman/cli/support.py#L88), you will have to specify the toolkit or googleapis under local_paths config, like below:

    local_paths:
      googleapis: /foo/bar/googleapis

Could you give that a try?

**Comment by ethanbao** [comment]
Thanks for confirming that. I will turn artman user config into a protobuf so that we can do the validation and documentation easier.

**Comment by geigerj** [comment]
It would be great to have documentation (and maybe validation) for the user config. Additionally, better error messages might be helpful; for example, if a path is not found, the tool could hint to check the `local_paths` section of the user config. We should also rename "googleapis" to "root-dir" for consistence.

**Comment by ethanbao** [comment]
All points accepted.

**Comment by ethanbao** [comment]
Fixed by https://github.com/googleapis/artman/pull/389
