### ISSUE TITLE
File permissions issue if generation fails

### ISSUE THREAD

**Issue by geigerj** [googleapis/artman#314]
Prior to #313, `artman` failed mid-generation when running in Docker mode (`protoc` succeeded, but `toolkit` failed). The `artman-genfiles` output directory contained files owned by `root`, making them non-editable by the user. It should be investigated whether the file owner/permission change fails to happen if an exception occurs in the middle of generation, and if so, it should be fixed so that the user is given permissions on output even when generation fails.

**Comment by ethanbao** [comment]
Fixed in https://github.com/googleapis/artman/pull/322
