### ISSUE TITLE
proto is already defined error

### ISSUE THREAD

**Issue by andreamlin** [googleapis/artman#321]
I'm trying to generate the gapic for bigtable, so I ran 
```
artman --config google/bigtable/admin/artman_bigtable_admin.yaml --verbose  generate java_gapic
```
but it fails with 
```
table.proto:63:10: "google.bigtable.admin.v2.Table.name" is already defined in file "google/bigtable/admin/v2/table.proto".
table.proto:68:29: "google.bigtable.admin.v2.Table.column_families" is already defined in file "google/bigtable/admin/v2/table.proto".
table.proto:75:24: "google.bigtable.admin.v2.Table.granularity" is already defined in file "google/bigtable/admin/v2/table.proto".
...
```

This is being run in the latest Docker image.

If I remove the *.proto files from the googleapis/ directory, then artman does successfully generate the gapic/protos/grpc files.

**Comment by ethanbao** [comment]
I saw the issue in both googleapis/artman:0.5.1 image and artman:0.5.0 image (using the --image flag like below). Can you check the proto definition?

    artman --image googleapis/artman:0.5.0 --config google/bigtable/admin/artman_bigtable_admin.yaml --verbose  generate java_gapic

**Comment by ethanbao** [comment]
I actually cannot repro the error you saw, below is what I got. Can you confirm that you don't have local changes to bigtable IDL including yamls and protos.

bigtable_table_admin.proto: warning: Import google/protobuf/duration.proto but not used.
bigtable_table_admin.proto: warning: Import google/protobuf/timestamp.proto but not used.
bigtable_table_admin.proto: warning: Import google/longrunning/operations.proto but not used.
common.proto:32:3: "google.bigtable.admin.v2.STORAGE_TYPE_UNSPECIFIED" is already defined in file "google/bigtable/admin/v2/common.proto".
common.proto:32:3: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "STORAGE_TYPE_UNSPECIFIED" must be unique within "google.bigtable.admin.v2", not just within "StorageType".
common.proto:35:3: "google.bigtable.admin.v2.SSD" is already defined in file "google/bigtable/admin/v2/common.proto".
common.proto:35:3: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "SSD" must be unique within "google.bigtable.admin.v2", not just within "StorageType".
common.proto:38:3: "google.bigtable.admin.v2.HDD" is already defined in file "google/bigtable/admin/v2/common.proto".
common.proto:38:3: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "HDD" must be unique within "google.bigtable.admin.v2", not just within "StorageType".
common.proto:30:6: "google.bigtable.admin.v2.StorageType" is already defined in file "google/bigtable/admin/v2/common.proto".
common.proto: warning: Import google/protobuf/timestamp.proto but not used.

**Comment by andreamlin** [comment]
I did have to remove at least 3 proto files, two of which were data.proto and common.proto, so yes I did get your error at some point after removing just data.proto.

This is a fresh clone of googleapis.

**Comment by ethanbao** [comment]
The error is thrown by protoc when compiling protos and the proto files are hosted in googleapis repo. Below is the protoc command that artman executs:

    protoc --proto_path=/googleapis --proto_path=/usr/local/google/home/cbao/GitRepo/googleapis/google/bigtable/admin/v2 --proto_path=/root/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protobuf-java/3.4.0/b32aba0cbe737a4ca953f71688725972e3ee927c/output --include_imports --include_source_info -o /usr/local/google/home/cbao/GitRepo/googleapis/artman-genfiles/google-cloud-bigtable-admin-v2.desc /usr/local/google/home/cbao/GitRepo/googleapis/google/bigtable/admin/v2/instance.proto /usr/local/google/home/cbao/GitRepo/googleapis/google/bigtable/admin/v2/bigtable_table_admin.proto /usr/local/google/home/cbao/GitRepo/googleapis/google/bigtable/admin/v2/common.proto /usr/local/google/home/cbao/GitRepo/googleapis/google/bigtable/admin/v2/table.proto /usr/local/google/home/cbao/GitRepo/googleapis/google/bigtable/admin/v2/bigtable_instance_admin.proto

If some proto files have conflicting proto elements defined, please reach out to the API team. I don't see why this is an artman bug.

**Comment by andreamlin** [comment]
I'm guessing that it's compiling `common.proto` that's located in the `--proto_path=/usr/local/google/home/cbao/GitRepo/googleapis/google/bigtable/admin/v2` directory along with the later parameter `/usr/local/google/home/cbao/GitRepo/googleapis/google/bigtable/admin/v2/common.proto`. 

Don't artman users generally compile protos with the proto files in the googleapis repo? How can I get around this?

**Comment by ethanbao** [comment]
The flag and arg don't conflict syntax-wise. The first specify the location where the proto lives (which could contain much more protos), the second arg is to specify the proto files that should be compiled into proto descriptor. 

I tried to build pubsub java and below is the protoc part. Note: pubsub java_gapic generation is working.

    protoc --proto_path=/googleapis --proto_path=/googleapis/google/iam/v1 --proto_path=/usr/local/google/home/cbao/GitRepo/googleapis/google/pubsub/v1 --proto_path=/root/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protobuf-java/3.4.0/b32aba0cbe737a4ca953f71688725972e3ee927c/output --include_imports --include_source_info -o /usr/local/google/home/cbao/GitRepo/googleapis/artman-genfiles/google-cloud-pubsub-v1.desc /usr/local/google/home/cbao/GitRepo/googleapis/google/pubsub/v1/pubsub.proto /googleapis/google/iam/v1/iam_policy.proto /googleapis/google/iam/v1/policy.proto /googleapis/google/iam/v1/logging/audit_data.proto

While I can reproduce the problem on my local machine. It doesn't seem to be a problem in the continuous test (https://circleci.com/gh/googleapis/googleapis/804). I will take another look.

**Comment by ethanbao** [comment]
https://github.com/googleapis/artman/pull/323 has been merged to fix this issue. It is still pending on a release of artman, which shall be done within one hour.

**Comment by ethanbao** [comment]
googleapis-artman 0.5.2 is released to PyPI. I confirmed the command worked on my dev machine now.

Please re-open if the new version still doesn't work for you.
