### ISSUE TITLE
PHP move task fails when destination exists

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/artman#326]
This occurs only when generating artman_core, because gapic_code_dir is defined, but the code to clean the gapic_code_dir directory is not run.

See here: https://github.com/googleapis/artman/blob/master/artman/config/converter.py#L82 and here: https://github.com/googleapis/artman/blob/master/artman/tasks/protoc_tasks.py#L258

**Comment by vchudnov-g** [comment]
@michaelbausor Still an issue?

**Comment by michaelbausor** [comment]
No, we can close this
