### ISSUE TITLE
proto files not included in java jars

### ISSUE THREAD

**Issue by jhspaybar** [googleapis/artman#351]
As best I can tell, this is where com.google.api.grpc:proto-google-common-protos from.  If not, please redirect me.  I also opened an issue over at grpc-java here https://github.com/grpc/grpc-java/issues/3873 as well.  It appears between version 0.1.6 of 0.1.9(and since then) the proto files are no longer published in the jar published to maven central.  This means that proto files expecting to import these files and have them be present when using the gradle protobuf plugin are unable to find the files.  Is there an alternative dependency I should be targeting if I want the proto files in a jar for further import and use?

**Comment by ethanbao** [comment]
@garrettjonesgoogle, I believe this is an intended change. Can you confirm?

**Comment by garrettjonesgoogle** [comment]
I took a look and I see that 0.1.9 is the first version missing the protos from grpc-google-common-protos; this was the same point in time that proto-google-common-protos was introduced. Basically, the proto-generated model classes went to the proto- package and the grpc-generated stubs stayed in the grpc- package; somehow, the raw protos themselves were dropped completely and don't appear in either. I checked one other package to see if this happened across the board, and appears true of grpc-google-cloud-logging-v2 / proto-google-cloud-logging-v2 too. 

I was never aware of this change, and I assumed we were still bundling the proto files. Someone else might have knowingly made this change and it slipped under my radar; there is no particular reason we can't bundle them in - I think it might have been convenience that led to dropping them.

I am in full support of adding the proto files back.

**Comment by ethanbao** [comment]
Thank you, Garrett. Shall we keep this github issue to track this or you prefer the one created under grpc/grpc-java, or maybe create a new one under GoogleCloudPlatform/google-cloud-java?

**Comment by garrettjonesgoogle** [comment]
GRPC isn't really the right place since we own the infrastructure that does this. For candidate repos for the issue, I would say googleapis/artman or googleapis/toolkit.

**Comment by jhspaybar** [comment]
Thank you for taking a look. I look forward to seeing these packaged again!

**Comment by jhspaybar** [comment]
Any updates if/where these might be getting published again?

**Comment by garrettjonesgoogle** [comment]
We have made the code fix, but we don't have a schedule yet for publishing the update.

**Comment by garrettjonesgoogle** [comment]
This has been released - version 1.0.5.
