### ISSUE TITLE
Can't find generated files after "publish --dry-run"

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/artman#365]
When I use `publish --dry-run`, I can't see the generated output anywhere locally. I would expect to be able to see it locally, either in the location used by the `generate` command or as a commit in the local clone of the repository specified in my publish target.

Details:

I ran `artman ... publish --dry-run --target staging go_gapic` (with the staging target specifying a github repo). The artman output shows 
```artman> Formatting files in /tmp/artman/UUID/googleapis/artman-genfiles/gapi-cloud-library_example-go.```
but when I then inspect the output directory,  
* `artman-genfiles/gapi-cloud-library_example-go` is not present 
* `artman-genfiles/go/` is empty
* I see no go source files anywhere: not for the library and not for the protos.
* The local clone of the repo specified in my publish target does not contain the generated library files either

In contrast, when I run `artman ... generate go_gapic`, the output still shows 
```artman> Formatting files in /tmp/artman/UUID/googleapis/artman-genfiles/gapi-cloud-library_example-go.```
When I inspect the output directory, I see the generated library files under `gapi-cloud-library_example-go/` and the generated protos under `go/`.

**Comment by ethanbao** [comment]
There was once a bug that the toolkit is returning zero status code even if the generation fails. That bug was recently fixed. Can you retry and see whether you are seeing an error instead of a success without output?

**Comment by ethanbao** [comment]
Please reopen if you see this problem again with artman version 0.6.0 and above.
