### ISSUE TITLE
Confusing behavior when using alternative googleapis dir

### ISSUE THREAD

**Issue by geigerj** [googleapis/artman#374]
### What

When `artman` is used in a root directory other than the `googleapis` directory configured in the artman user config, the behavior is confusing; artman ignores the working directory and resolves the input and output paths relative to the `googleapis` directory specified in the user config.

### Repro

.artman/config.yaml:

```
...
local_paths:
  googleapis: ~/repos/gapi-dev/googleapis
  toolkit: ~/repos/gapi-dev/toolkit
```

Commands:
```
$ cd ~/repos/gapi-dev/other-googleapis
$ artman --config path/to/artman_config.yaml generate ruby_gapic
...
artman> Code generated: /usr/local/google/home/jgeiger/repos/gapi-dev/googleapis/{output_path}
```

### Workaround

Specify the `root-dir` flag:

```
$ cd ~/repos/gapi-dev/other-googleapis
$ artman --config path/to/artman_config.yaml --root-dir . generate ruby_gapic
...
artman> Code generated: /usr/local/google/home/jgeiger/repos/gapi-dev/other-googleapis/{output_path}
```

### Observed behavior

The code is generated in the `googleapis` directory, not the `other-googleapis` directory, and the output files are from the protos in the `googleapis` directory, not the `other-googleapis` directory.

### Expected behavior
I'm unsure why the user config is needed at all here, since the information about input path resolution should be possible based on the artman config. It would be preferable if `artman` does not rely on a user config for path resolution, and instead resolves paths relative to the artman config.

**Comment by ethanbao** [comment]
Fixed by https://github.com/googleapis/artman/pull/389
