### ISSUE TITLE
Make more packman flags configurable

### ISSUE THREAD

**Issue by geigerj** [googleapis/artman#39]
In particular, the `--services_root` and `--include_path` flags for `gen-api-package` are useful for APIs that are not in the googleapis repo,

**Comment by garrettjonesgoogle** [comment]
Is this obsolete since we are moving away from Packman now?

**Comment by geigerj** [comment]
Yup, let's close this out. (Unlike Packman, the new flow doesn't care whether the input protos are located in googleapis.)
