### ISSUE TITLE
Figure out why baselines aren't used in unit tests

### ISSUE THREAD

**Issue by garrettjonesgoogle** [googleapis/artman#420]
Deleting the baselines from https://github.com/googleapis/artman/tree/master/test/testdata (with the exception of `google-cloud-fake-v1_package.yaml`) doesn't cause any tests to fail. I have verified this is true all the way back to commit https://github.com/googleapis/artman/commit/0995314b8003173db52dd156e349c6136c8fa04a (from 18 Apr, 2017). I'd like to figure out if this was intentional or accidental, and if we want to get them working again or just delete them.

**Comment by lukesneeringer** [comment]
This was accidental but I assert it is desirable.
When I did the refactor, I moved this conceptually into tests [like this one](https://github.com/googleapis/artman/blob/master/test/tasks/test_gapic.py#L28-L57). This conceptually does something similar, but usually for subsets of the entire thing.

I propose the fix should just be to delete the extraneous files, which are almost certainly a year out of date. (Thanks for catching that!) I do not feel like we are losing anything by not having this.
