### ISSUE TITLE
Src protos not copied when multiple directories specified

### ISSUE THREAD

**Issue by eoogbe** [googleapis/artman#435]
In Python generation, only the protos from the `src_proto_paths` field of the artman config that live in the same directory as the services gets copied to the destination folder.

[`self.exec_command(['mv', os.path.join(src, 'proto'), target])`](https://github.com/googleapis/artman/blob/master/artman/tasks/python_grpc_tasks.py#L202)  ignores protos outside of the ones contained in the service directory. This command should include every directory listed in `src_proto_paths`.

**Comment by tswast** [comment]
@lukesneeringer Any word on this? It's blocking some BigQuery-related library releases.

**Comment by tswast** [comment]
P2 does not seem right as this is blocking API generation for some of the products I work on.

**Comment by lukesneeringer** [comment]
Okay, I looked into this more today.
There are several issues here and digging through all of them will be difficult.

However, for this particular API, I assert you should just comment out the `v3/` protos on lines 9 and 10 in the artman YAML. This is not a workaround; I assert they actually should not be there and their presence is a misconfiguration.

I have tested that and established that it does the right thing. (Note that you will still have to manually handle the dependency on the root API.)

**Comment by vchudnov-g** [comment]
@lukesneeringer Update?

**Comment by noahdietz** [comment]
@lukesneeringer any update here? Thanks.

**Comment by lukesneeringer** [comment]
@tswast Are you able to generate the API now?

**Comment by tswast** [comment]
Yes, but that's because the API moved into a single directory in preparation for beta.

**Comment by tswast** [comment]
Unless it's blocking someone else, we can drop back to P2 probably.

**Comment by vchudnov-g** [comment]
@lukesneeringer : Any updates (to stay in SLO)?

**Comment by noahdietz** [comment]
@lukesneeringer as mentioned earlier in the thread, there might be multiple issues here. Should we break things up into individual issues or is there an enumeration of fixes we can include here as an update? Thanks!

**Comment by vchudnov-g** [comment]
@lukesneeringer Any updates? We're out of SLO (>3mo since the last update)

**Comment by vchudnov-g** [comment]
Moving to P3 as we are deprecating artman, so this may not be fixed. @vam-google , please feel free to chime in.

**Comment by vam-google** [comment]
Python generaton is migrated to bazel. Closing.
