### ISSUE TITLE
Go: release level not being considered

### ISSUE THREAD

**Issue by jadekler** [googleapis/artman#548]
We recently set [the spanner release level to GA](https://github.com/googleapis/googleapis/blob/master/google/spanner/artman_spanner.yaml#L31). However, when we regenerate gapics, the [alpha notice](https://github.com/googleapis/google-cloud-go/blob/master/spanner/apiv1/doc.go#L20) doesn't get removed as expected. I expect that this is a bug?

**Comment by andreamlin** [comment]
I know that the GAPIC config at spanner_gapic.yaml release levels will affect the alpha notice. I'm not sure what the artman config (artman_spanner.yaml) release levels do...

I would expect that porting the change over to spanner_gapic.yaml will result in the behavior you expect.

**Comment by jadekler** [comment]
Gotcha - thanks!
