### ISSUE TITLE
Switch to composer from pear for PHP dependencies

### ISSUE THREAD

**Issue by andreamlin** [googleapis/artman#555]
New images of artman won't build because it requires the `pear` util, whose server has been hacked and is now down.

failure log https://circleci.com/gh/googleapis/artman/8964

pear's website: http://pear.php.net/
arstechnica article: https://arstechnica.com/information-technology/2019/01/pear-php-site-breach-lets-hackers-slip-malware-into-official-download/

We can switch to `composer` instead of pear.

**Comment by alexander-fenster** [comment]
Why me?  :)

@michaelbausor asking you as a PHP lead :) So we've got this in our `Dockerfile`:

```
Step 24/37 : RUN pear install PHP_CodeSniffer-2.9.1   && curl -L https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.2.7/php-cs-fixer.phar -o /usr/local/bin/php-cs-fixer   && chmod a+x /usr/local/bin/php-cs-fixer   && cd /
 ---> Running in 763fd770d982
No releases available for package "pear.php.net/PHP_CodeSniffer"
install failed
The command '/bin/sh -c pear install PHP_CodeSniffer-2.9.1   && curl -L https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.2.7/php-cs-fixer.phar -o /usr/local/bin/php-cs-fixer   && chmod a+x /usr/local/bin/php-cs-fixer   && cd /' returned a non-zero code: 1
Exited with code 1
```

These commands are called from here:

https://github.com/googleapis/artman/blob/5bcb88802ad9668fd6e6d2a7a15642ae6a340137/Dockerfile#L129-L132

Do you know the correct way of fixing it?

Thanks!

**Comment by andreamlin** [comment]
@alexander-fenster haha meant to just cc you

it's a blocker for me, so i'll look into it first. I asked michael about using composer instead and that seems like a good alternative.

**Comment by michaelbausor** [comment]
Another option that may be easier that using composer is to replace the `pear install` with a curl or wget to pull the .phar files from here: https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/2.9.1. This is similar to the following three lines that pull in php-cs-fixer.

There are instructions here on using curl or wget: https://github.com/squizlabs/PHP_CodeSniffer#installation. To keep things exactly the same, we should grab the 2.9.1 release from github.

That said, composer is totally fine too, whichever is easiest.

**Comment by andreamlin** [comment]
Fixed in https://github.com/googleapis/artman/pull/557. Closing this.
