### ISSUE TITLE
Python: include enums in generated documentation

### ISSUE THREAD

**Issue by tswast** [googleapis/artman#579]
The documentation for the `google.cloud.someapi.gapic.enums` doesn't currently get generated.

Unfortunately, since many (all?) enum classes are inner classes, Sphinx's `automodule` directive doesn't seem to support that. Instead, it appears you can use `autoclass` for each class in the enums file.

Also, I don't see type hints indicating that these enums are used in the docstrings for the proto classes for which they are relevant.

**Comment by mik-laj** [comment]
Is there any progress in this issues?

**Comment by nuclearpinguin** [comment]
@lukesneeringer any update on this issue?

**Comment by sgreenberg** [comment]
@alexander-fenster - Luke suggested you should take this? (I don't have permissions to assign it to you.)

**Comment by tswast** [comment]
CC @software-dov as well, as I assume this is relevant to the microgenerator.

**Comment by alexander-fenster** [comment]
I think it's related to the specific language (Python) and not the artman tool itself, so I'd better transfer to @software-dov directly. Dov, feel free to ping me, we might want to look at this together to understand how to fix it in monolith (I assume you know how to fix it in the microgenerator if the problem exists there).
