### ISSUE TITLE
Emit better error if gen-api-package cannot be found

### ISSUE THREAD

**Issue by bjwatson** [googleapis/artman#60]
Steps to reproduce:

1) In a complete repository checkout (including artman and toolkit), `cd artman`
2) Confirm that `gen-api-package` is _not_ in your PATH variable
3) Run the JavaGrpcClientPipeline or PythonGrpcClientPipeline

Expected result:
A helpful error should indicate that the gen-api-package command cannot be found.

Actual results:
An obscure `OSError: [Errno 2] No such file or directory` error is emitted.

**Comment by ethanbao** [comment]
gen-api-package is provided by packman which is no longer used in artman. Close this bug as obsolete.
