### ISSUE TITLE
Nested package proto imports fail for Python

### ISSUE THREAD

**Issue by Katee** [googleapis/artman#610]
I'm not able to get Python GAPIC generation to work when using nested packages. Here's an example: https://github.com/Katee/artman-python-example

Running `artman --verbose --config artman_grafeas_v1.yaml generate python_gapic` in that repo returns:

```
v1/pkga/pkga.proto: File not found.
v1/pkgb/pkgb.proto: File not found.
grafeas_v1/proto/grafeas.proto: Import "v1/pkga/pkga.proto" was not found or had errors.
grafeas_v1/proto/grafeas.proto: Import "v1/pkgb/pkgb.proto" was not found or had errors.
grafeas_v1/proto/grafeas.proto:29:3: "grafeas.v1.pkga.PackageA" is not defined.
grafeas_v1/proto/grafeas.proto:30:3: "grafeas.v1.pkgb.PackageB" is not defined.
```

Generation for all other languages does not return an error.

**Comment by eoogbe** [comment]
Getting a 404 for the example code. Can you elaborate a little on the problem? What does your directory structure look like?

**Comment by Katee** [comment]
Sorry, I could have closed this bug earlier.

The problem is I couldn't get Python generation to work without the package directive in the `*.proto` files matching the directory structure of the protos. This is already a known limitation of the Python client library generation.
