### ISSUE TITLE
Samples are not being generated (as of 0.29.1)

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/artman#653]
20 minutes ago my sample builds started failing.

I can generate fine w/ 0.29.0

I get no samples as of 0.29.1

@googleapis/samplegen @alexander-fenster

**Comment by alexander-fenster** [comment]
#656 will help passing the right parameter to gapic-generator but the main problem should be fixed in gapic-generator. After https://github.com/googleapis/gapic-generator/pull/2828 it requires some extra parameters in addition to `dev_samples`.

**Comment by beccasaurus** [comment]
PLEASE UPGRADE TO P0

ping on status?

**Comment by vchudnov-g** [comment]
https://github.com/googleapis/gapic-generator/pull/2860 should have fixed this, but we need to generate a new artman release.
