### ISSUE TITLE
Add sample generation to golden test (to catch samplegen regressions)

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/artman#654]
We just accidentally pushed a release which broke samplegen – no sample files being output:
 - https://github.com/googleapis/artman/issues/653

To catch this, let's update the golden library so it has at least 1 code sample.

Here are some of the bits I've found out so far (really @alexander-fenster did) ~

 - We'll add the names of the generated sample files here:

https://github.com/googleapis/artman/blob/22e143fcdb01e18caa6fc58e1ae3d5d3e2f90dce/test/golden/library_example.golden#L10

 - We'll need to add `--generator-args="--dev_samples"` to these gapic invocations:

https://github.com/googleapis/artman/blob/22e143fcdb01e18caa6fc58e1ae3d5d3e2f90dce/.circleci/config.yml#L42

> _I think? If these are the golden?_

Here's where the golden gapics are invoked so maybe I'm wrong about it being part of the smoketest above :)

https://github.com/googleapis/artman/blob/22e143fcdb01e18caa6fc58e1ae3d5d3e2f90dce/test/golden/artman_golden_test.py#L51

So, yeah. Need to dive in more, find the source for the golden library (proto + gapic config) and add samples.

@googleapis/samplegen 
@alexander-fenster

**Comment by alexander-fenster** [comment]
These are two different things: golden

https://github.com/googleapis/artman/blob/22e143fcdb01e18caa6fc58e1ae3d5d3e2f90dce/.circleci/config.yml#L34-L40

and smoke

https://github.com/googleapis/artman/blob/22e143fcdb01e18caa6fc58e1ae3d5d3e2f90dce/.circleci/config.yml#L41-L59

Golden run just one example (library, the one with bookshelves and stuff) and checks the list of generated files (compares with the `.golden` file).

Smoke runs a list of commands generating clients for real APIs and just checks that the exit code is 0.

You might need to add samplegen to both.

**Comment by vchudnov-g** [comment]
Bumping to P0 enhancement.
