### ISSUE TITLE
Stop using packman for Ruby gRPC client generation

### ISSUE THREAD

**Issue by jmuk** [googleapis/artman#72]
Derived from #69:

Currently Ruby gRPC client pipeline use packman to generate gRPC files. However, that does not fit with the design of gcloud-ruby, where a package contains all of hand-written layers, Gapic-generated files, and gRPC-generated files.
That is Cloud APIs only, but there are no strong reasons to split packages for Gapic files and gRPC files in Ruby.

Because of that, we should stop using packman for Ruby's client pipeline. Instread, similar to Java, we should use protoc_tasks we already have.

Also, from https://github.com/googleapis/artman/issues/69#issuecomment-242172115,

> Currently we get protoc from linuxbrew here: https://github.com/grpc/homebrew-grpc
> That site indicates that the linuxbrew method is deprecated for all languages except C/C++. 

Therefore, Ruby will use grpc-tools rubygem (https://rubygems.org/gems/grpc-tools).

Cc: @bjwatson @geigerj

**Comment by jmuk** [comment]
@Landrito, this is the one we chatted.

**Comment by Landrito** [comment]
Gotcha, I'll look into it!

**Comment by garrettjonesgoogle** [comment]
I did want to note that the "similar to Java" comment is not correct - Java was converted to use packman (opposite conversion as proposed here for Ruby). 

At a higher level, I'm not a huge fan of this mix of doing some generation in packman and some in artman. It seems preferable to make only one component responsible.

**Comment by jmuk** [comment]
Hmmm, I didn't know that, thank you for the info.

Then, I am quite unsure what needs to be done here... possibly:
- fix packman templates -- remove README or gemspec files. Then purely run protoc.
- modify artman task to copy the packman results to the final_repo_dir
?

**Comment by garrettjonesgoogle** [comment]
I think it could make sense for artman to copy the packman results to final_repo_dir.

**Comment by Landrito** [comment]
For clarifications sake, we are copying rather than generating directly to the final_repo_dir to avoid the case where generation fails partway through only generating some of the files?

**Comment by garrettjonesgoogle** [comment]
Yes, we always generate directly into a temp dir under output/.

**Comment by jmuk** [comment]
Let me reopen this, I think the original description still makes sense.

The justification is that we actually don't need package definition files for gRPC clients, because we don't create an independent package for gRPC client. Instead Gapic client package should contain .rb files for both Gapic and gRPC clients. Now it's better for artman to invoke proto-compiler rather.
