### ISSUE TITLE
artman: pull the artman image for me

### ISSUE THREAD

**Issue by jadekler** [googleapis/artman#732]
We don't pin to latest docker image, but there's also no way for a user to get all versions of a docker image. That leads to a kinda crummy UX: I always have to run googleapis-artman, then get an error, then go docker pull for whatever version googleapis-artman is looking for.

Per @lukesneeringer suggestion: can we just have the python program do the pull, since it already knows which version it needs?

**Comment by jadekler** [comment]
Ping - anyone who can pick this up? It continues to be a huge QOL nuisance. :/

**Comment by xiaozhenliu-gg5** [comment]
Ping Alex@ to take a look at this issue, not sure how long it takes to pull the image.

**Comment by alexander-fenster** [comment]
@jadekler I see your pain :)  I will see if it's an easy fix to add `docker pull` there.

**Comment by alexander-fenster** [comment]
No way we are going to fix anything in artman.  Deprecated it is.
