### ISSUE TITLE
Remote execution fails when local_repo is too big

### ISSUE THREAD

**Issue by geigerj** [googleapis/artman#74]
### Observed behavior

When the directory specified by the local_repo dir is too big, remote execution fails with the confusing message "taskflow.exceptions.StorageFailure: Storage backend internal error". This is a frequent error case if the directory pointed to is actually a git repo (i.e., also contains associated git metadata).
### Expected behavior

Artman should validate that the size of local_repo is < 1 MB.
### Action

Accumulate the size of local_repo here: https://github.com/googleapis/artman/blob/e83b08313c7fff2cb1f5ca6f716220050d1d4fd9/execute_pipeline.py#L221
and throw a meaningful exception if it is too big.

**Comment by geigerj** [comment]
Users are not seeing the error message. Re-opening.

**Comment by ethanbao** [comment]
Became obsolete as we no longer promote such remote execution.
