### ISSUE TITLE
GapicConfigPipeline can overwrite file in remote environment

### ISSUE THREAD

**Issue by bjwatson** [googleapis/artman#80]
### What:

GapicConfigPipeline currently raises a ValueError if the target GAPIC config file already exists. This can be disabled in a remote environment.
### Why:

This test is justified in the local environment, because GapicConfigPipeline can overwrite the GAPIC config in a developer's [`googleapis`](https://github.com/googleapis/googleapis) sandbox that might have unstaged changes. Not having this test is potentially surprising and frustrating for developers using the local environment.

For developers using a remote environment, there is no such danger. GapicConfigPipeline does not touch an active sandbox in this mode, and instead delivers a tarball of the [`googleapis`](https://github.com/googleapis/googleapis) repository with generated changes overlaid. Having this test is potentially surprising and frustrating for developers using a remote environment, because they have to know that they need to temporarily modify their artman config to re-generate a GAPIC config file.
### How:

The test is in [`pipeline.tasks.gapic_tasks.GapicConfigMoveTask._move_to()`](https://github.com/googleapis/artman/blob/master/pipeline/tasks/gapic_tasks.py#L64).

**Comment by bjwatson** [comment]
@shinfan @ethanbao This issue is relevant to the email discussion about self-service today. An enhancement that Ethan proposed is to also allow this in a local environment, but to make a copy of the current GAPIC config if one exists (e.g. foobar -> foobar.sav).

**Comment by geigerj** [comment]
At the very minimum we should give a meaningful error message in this case. Currently, artman writes "`BUILD SUCCESSFUL`" to the log and then fails, which is very unhelpful.

**Comment by ethanbao** [comment]
Became obsolete as we no longer support such remote execution mode.
