### ISSUE TITLE
Confusing failure in remote mode for GAPIC config pipeline

### ISSUE THREAD

**Issue by geigerj** [googleapis/artman#91]
### Expected behavior

If a GAPIC config already exists and the pipeline is running in remote mode, either
- artman fails and returns a meaningful error message, or
- artman overwrites the config in the archive that is downloaded
### Observed behavior

Artman fails with no information. Logs indicate only that the config was generated successfully, since the failure occurs at the copying stage -- after the config is actually generated.
### Context

Artman does not automatically overwrite existing configs because of the risk of overwriting uncommitted manual edits, which occur frequently in the development process. However, this risk exists only when running Artman in local mode, since in remote mode, nothing is ever overwritten on the local machine. We can therefore safely overwrite.

If detecting the environment (local/remote) is complicated, a clear error message is a good short-term solution.

**Comment by ethanbao** [comment]
Became obsolete as we no longer support such remote execution mode.
