### ISSUE TITLE
Move Python gRPC packages to google.cloud.grpc namespace

### ISSUE THREAD

**Issue by bjwatson** [googleapis/artman#97]
### What:

Change the Python path for gRPC-generated cloud APIs to `google.cloud.grpc.{api}.{version}`.
### Why:

We have to do this for the Cloud ML libraries, because they currently define the `google.cloud.{api}` namespace, which interferes with the [google-cloud-python team](https://github.com/GoogleCloudPlatform/google-cloud-python) putting package members into `google.cloud.{api}` for user convenience. We also want to do the same for other gRPC packages for consistency.
### How:

Copy proto to the desired path before building the Python gRPC code. Some hand-edits are needed for dependencies between gRPC files in the same package, since the import path seems to be the only thing that uses the proto package (FYI @nathanielmanistaatgoogle). An [example](https://github.com/googleapis/api-client-staging/pull/3/commits/dad7708a8124afbd869d9427f33361f1f42d6e5b) occurs in Cloud Vision.

Note that `packman` cares what the proto package is, so I had to use `protoc` directly for doing this by hand. The function [`computePkg()`](https://github.com/googleapis/packman/blob/0f31e39bdbe950abcda271898de9f74a7b2f3ec1/lib/api_repo.js#L946) looks it up and uses it for setting up its arguments to call `protoc`. This trips up the [`checkDir` calculation](https://github.com/googleapis/packman/blob/0f31e39bdbe950abcda271898de9f74a7b2f3ec1/lib/api_repo.js#L985) and the [include path calculation](https://github.com/googleapis/packman/blob/0f31e39bdbe950abcda271898de9f74a7b2f3ec1/lib/api_repo.js#L1030). We need to change this logic somehow. Should `packman` really care what the proto package says?

We also need a way of telling `toolkit` about the gRPC path, so it generates its import statements accordingly.

**Comment by geigerj** [comment]
I think the fact that `packman` deals with the protos directly at all is problematic. As discussed some time ago, the reason `packman` runs `protoc` (instead of `artman` invoking `protoc` directly via a task) is a historical accident. As an implementation detail, I propose we move Python gRPC generation off packman as part of this fix.

**Comment by geigerj** [comment]
As discussed offline, I think it's hackish to be editing the `_pb2` files and would prefer this was handled upstream. I've filed https://github.com/grpc/grpc/issues/8492 to that end.

However, for expediency I'll try to figure to automate this described in `artman` in the meantime.

**Comment by bjwatson** [comment]
@geigerj I agree with both proposals:

1) Let's fix this right. I agree that we should move the `protoc` call into `artman`. What does that mean for generating `googleapis-common-protos`? Would we still leave `protoc` calling code in `packman` for this?

2) We need to do something in `packman` for schedule reasons, but I agree that pushing this down to `protoc` future-proofs us against changes they might make down the line.

**Comment by geigerj** [comment]
I have confirmed that the latest versions of artman and toolkit produce the right package names for `logging`.
